_target_: pytorch_lightning.Trainer
precision: ${precision}
max_epochs: ${n_epochs}
check_val_every_n_epoch: ${val_freq}
deterministic: False
num_sanity_val_steps: 0
log_every_n_steps: 1
flush_logs_every_n_steps: 20
progress_bar_refresh_rate: 5