_target_: src.models.KernelAgg
lambda_reg: 1e-3
learn: True
kernel:
  _target_: gpytorch.kernels.ScaleKernel
  base_kernel:
    _target_: gpytorch.kernels.RBFKernel
    ard_num_dims: ${dataset.num_covariates}
